name: CD to AWS EKS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # -------------------------------------------------------
    # 1️⃣ Login to ECR
    # -------------------------------------------------------
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # -------------------------------------------------------
    # 2️⃣ Build & Push Docker Image
    # -------------------------------------------------------
    - name: Build, Tag, and Push Docker Image
      run: |
        IMAGE_URI=695880279609.dkr.ecr.us-east-1.amazonaws.com/student-management:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    # -------------------------------------------------------
    # 3️⃣ Update kubeconfig for EKS
    # -------------------------------------------------------
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name student-app-cluster

    # -------------------------------------------------------
    # 4️⃣ Deploy to Kubernetes
    # -------------------------------------------------------
    - name: Deploy to EKS
      run: |
        kubectl set image deployment/student-app student-app=695880279609.dkr.ecr.us-east-1.amazonaws.com/student-management:latest
        kubectl rollout status deployment/student-app
